name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildandpushdocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Build new docs
      run: |
        npm i
        npm run build:storybook
    - name: Deploy new GH page
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh_page
        FOLDER: docs
        ACCESS_TOKEN: ${{ github.token }}
