name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildandpushdocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Build new docs
      run: |
        npm i
        npm run build:storybook
        git config --local user.name "Github Action"
        git config --local user.email "action@github.com"
        npm run deploy
